DROP TABLE IF EXISTS ImageAutographs;
DROP TABLE IF EXISTS TextAutographs;
DROP TABLE IF EXISTS UserAccess;
DROP TABLE IF EXISTS Photos;
DROP TABLE IF EXISTS Albums;


CREATE TABLE Albums (
    ID      INTEGER   PRIMARY KEY AUTOINCREMENT,
    UserID  INTEGER   NOT NULL,
    Title   TEXT      NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE Photos (
    ID         INTEGER   PRIMARY KEY AUTOINCREMENT,
    AlbumID    INTEGER   NOT NULL,
    UploaderID INTEGER,
    Url        TEXT      NOT NULL,
    Created    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (AlbumID) REFERENCES Albums(ID) ON DELETE CASCADE,
    FOREIGN KEY (UploaderID) REFERENCES Users(ID) ON DELETE SET NULL
);

CREATE TABLE UserAccess (
    AlbumID     INTEGER,
    UserID      INTEGER,
    AccessLevel INTEGER NOT NULL DEFAULT 2, -- crd (4:create|2:read|1:delete)

    FOREIGN KEY (AlbumID) REFERENCES Albums(ID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE TextAutographs (
    ID       INTEGER   PRIMARY KEY AUTOINCREMENT,
    PhotoID  INTEGER   NOT NULL,
    AuthorID INTEGER   NOT NULL,
    Text     TEXT      NOT NULL,
    Created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PhotoID) REFERENCES Photos(ID) ON DELETE CASCADE,
    FOREIGN KEY (AuthorID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE ImageAutographs (
    ID       INTEGER   PRIMARY KEY AUTOINCREMENT,
    PhotoID  INTEGER   NOT NULL,
    AuthorID INTEGER   NOT NULL,
    Url      TEXT      NOT NULL,
    Created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PhotoID) REFERENCES Photos(ID) ON DELETE CASCADE,
    FOREIGN KEY (AuthorID) REFERENCES Users(ID) ON DELETE CASCADE
);

